FROM golang:1.8.3

LABEL maintainer "marcelbelmont@gmail.com"

# Set Environment variables
ENV appDir /var/www/app

# Set the work directory
RUN mkdir -p ${appDir}
WORKDIR ${appDir}
ADD . ${appDir}

RUN go get gopkg.in/mgo.v2
RUN go get github.com/keimoon/gore
RUN go get github.com/gorilla/mux
RUN go get github.com/gorilla/handlers
RUN go get github.com/jbelmont/containerized-golang-and-vuejs/routes
RUN go get github.com/jbelmont/containerized-golang-and-vuejs/handlers
RUN go get github.com/jbelmont/containerized-golang-and-vuejs/model
RUN go get github.com/jbelmont/containerized-golang-and-vuejs/redis

RUN go build
